sudo: required
language: scala
jdk:
- openjdk8
- openjdk11
install: true
script: mvn test -B

matrix:
  allow_failures:
    - jdk: openjdk11
  fast_finish: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.nvm

before_cache:
  - rm -rf $HOME/.m2/repository/com/lightbend/lagom/sample/chirper

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2aa0aeda88d31fe293d4
    on_success: change
    on_failure: always
    on_start: never
